# Default values for trident
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ExternalSecret Configuration
secretStoreRef:
  name: vault-backend
  kind: ClusterSecretStore

# Maps to $gitroot/values-secret.yaml-template declaration
tridentFSX:
  key: secret/data/global/fsx-admin
  backendSecretName: backend-fsxn-secret
  mgmtLIF: ""
  svm: SVM1
  backends:
    nfs:
      storageDriverName: ontap-nas
      storagePrefix: trident_nfs
      defaults:
        snapshotDir: "true"
        nameTemplate: "{{ .config.StoragePrefix }}_{{ .volume.Namespace }}_{{ .volume.RequestName }}"
    iscsi:
      storageDriverName: ontap-san
      storagePrefix: trident_iscsi
