tridentFSX:
  mgmtLIF: 198.19.219.128
  clusterLIF: "198.19.219.70"
  svm: SVM1
  interclusterIPs:
    - 10.10.133.249
    - 10.10.144.21
  peer:
    mgmtLIF: "198.19.140.208"
    clusterLIF: "198.19.140.164"
    svm: SVM1
    interclusterIPs:
      - 10.100.156.219
      - 10.100.169.196
clusterGroup:
  name: hub
  argoCD:
    resourceHealthChecks:
      - kind: TridentOrchestrator
        group: trident.netapp.io
        check: |
          hs = {}
          if obj.status ~= nil and obj.status.status ~= nil then
            if obj.status.status == "Installed" then
              hs.status = "Healthy"
              hs.message = "Trident installation completed successfully."
            elseif obj.status.status == "Installing" then
              hs.status = "Progressing"
              hs.message = "Trident is currently installing."
            elseif obj.status.status == "Updating" then
              hs.status = "Progressing"
              hs.message = "Trident is currently updating."
            elseif obj.status.status == "Failed" then
              hs.status = "Degraded"
              hs.message = "Trident installation failed. Check operator logs."
            else
              hs.status = "Progressing"
              hs.message = "Trident status unknown or pending."
            end
          else
            hs.status = "Progressing"
            hs.message = "Awaiting TridentOrchestrator status."
          end
          return hs
  # Namespace is a dictionary for easier overriding (lists are supported as well)
  namespaces:
    open-cluster-management:
    vault:
    golang-external-secrets:
    trident:
    trident-protect:
    openshift-cnv:
  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.15
      # csv: advanced-cluster-management.v2.6.1
    trident:
      name: trident-operator
      namespace: openshift-operators
      channel: stable
      source: certified-operators
  argoProjects:
    - hub
    - trident
  # Explicitly mention the cluster-state based overrides we plan to use for this pattern.
  # We can use self-referential variables because the chart calls the tpl function with these variables defined
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml'
  # sharedValueFiles is a flexible mechanism that will add the listed valuefiles to every app defined in the
  # applications section. We intend this to supplement and possibly even replace previous "magic" mechanisms, though
  # we do not at present have a target date for removal.
  #
  # To replicate the "classic" magic include structure, the clusterGroup would need all of these
  # sharedValueFiles, in this order:
  #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.global.clusterVersion }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.clusterGroup.name }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml"
  #   - '/overrides/values-{{ $.Values.global.localClusterName }}.yaml'

  # This kind of variable substitution will work with any of the variables the Validated Patterns operator knows
  # about and sets, so this is also possible, for example:
  #   - '/overrides/values-{{ $.Values.global.hubClusterDomain }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.localClusterDomain }}.yaml'
  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      argoProject: hub
      chart: acm
      chartVersion: 0.1.*
    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      argoProject: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*
    trident:
      name: trident
      namespace: trident
      path: charts/all/trident
      argoProject: trident
    protect:
      name: trident-protect
      namespace: trident-protect
      argoProject: trident
      chart: trident-protect
      repoURL: https://netapp.github.io/trident-protect-helm-chart
      chartVersion: 100.2510.0
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: tp-webhook-tls
          jqPathExpressions:
            - .data
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: trident-protect-validating-webhook-configurations
          jqPathExpressions:
            - '.webhooks[].clientConfig.caBundle'
    protect-config:
      name: trident-protect-config
      namespace: trident-protect
      argoProject: trident
      path: charts/all/trident-protect-config
  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://validatedpatterns.io/patterns/multicloud-gitops/mcg-imperative-actions/
    jobs:
      - name: hello-world
        # ansible playbook to be run
        playbook: rhvp.cluster_utils.hello_world
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  managedClusterGroups:
    exampleRegion:
      name: secondary
      acmlabels:
        - name: clusterGroup
          value: secondary
          # helmOverrides:
          #   - name: foo
          #     value: bar
          # Before enabling cluster provisioning, ensure AWS and/or Azure
          #   credentials and OCP pull secrets are defined in Vault.
          #   See values-secret.yaml.template
          #
          # clusterPools:
          #  exampleAWSPool:
          #    name: aws-ap
          #    openshiftVersion: 4.10.18
          #    baseDomain: blueprints.rhecoeng.com
          #    platform:
          #      aws:
          #        region: ap-southeast-2
          #    clusters:
          #    - One
          #
          #  exampleAzurePool:
          #    name: azure-us
          #    openshiftVersion: 4.10.18
          #    baseDomain: blueprints.rhecoeng.com
          #    platform:
          #      azure:
          #        baseDomainResourceGroupName: dojo-dns-zones
          #        region: eastus
          #    clusters:
          #    - Two
          #    - Three
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main
#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: foo
#        value: bar
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
