---
global:
  pattern: netapp-dr-starter-kit
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  tridentProtect:
    appVault:
      enabled: true
      name: s3-appvault
      s3:
        bucketName: trident-protect-bucket
        region: us-west-1

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
