apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-wordpress-password
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: {{ .Values.wordpressSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        wordpress-password: |-
          {{ "{{ .password | trim }}" }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.wordpressSecret.vaultKey }}
        property: {{ .Values.wordpressSecret.property }}
