apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-trident-protect-kopia-password
  namespace: trident-protect
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: {{ .Values.kopiaSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        KOPIA_PASSWORD: |-
          {{ "{{ .kopiaPassword | trim }}" }}
  data:
    - secretKey: kopiaPassword
      remoteRef:
        key: {{ .Values.kopiaSecret.vaultKey }}
        property: {{ .Values.kopiaSecret.property }}
