apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-trident-backend-fsxn-secret
  namespace: trident
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
{{- with .Values.tridentFSX }}
  target:
    name: {{ .backendSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      data:
        password: |-
          {{ "{{ .password | trim }}" }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .key }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .key }}
        property: content
{{- end }}
