apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-iscsi
  annotations:
    storageclass.kubevirt.io/is-default-virt-class: 'true' 
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  sanType: "iscsi"
mountOptions:
   - discard
allowVolumeExpansion: true

