apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: snap-sched1
  namespace: my-vm
spec:
  appVaultRef: lab-vault
  applicationRef: my-vm
  backupRetention: "0" 
  enabled: true
  granularity: Custom
  recurrenceRule: |-
    DTSTART:20250430T000000Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  snapshotRetention: "3" 

